import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/header'
import Navbar from '../components/navbar'

export default function Home() {
  return (
    <div className={`flex flex-col`}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <div className = {`flex flex-row`}>
        <Navbar/>
      </div>
    </div>

  )
}
